import LocalizedStrings from 'react-localization';
 
export let strings = new LocalizedStrings({
 en:{
     lang: "العربية",
     sellingYourCarNow: "SELLING YOUR CAR NOW",
     easierThanEver: "IS EASIER THAN EVER",
     startToday: "Start Today",
     howItWorks: "How It Works ?",
     sellYourCarInThreeSimpleSteps: "Sell Your Car in Three Simple Steps",
     submitYourCar: "Submit Your Car",
     enterYourCarDetails: "Enter your car details for inspection on Emirates Auction.",
     receiveOffer: "Receive Valuation and Offer",
     weWillCheckCar: "We will check your car and provide you with approved purchase price.",
     getThePayment: "Get Your Payment",
     afterPriceIsAgree: "After a price is agreed for your car, we will exchange cash on a day that suits you.",
     yourCarWillBeSold: "Your car will be sold by bidding",
     startPriceItWillBeSold: "You set the starting price it will be sold for the highest bidder",
     youAreJustOneClick: "You are just one click away from selling your car",
     enterCarDetail: "Enter your Car Details",
     carBrand: "Car Make",
     carModel: "Car Model",
     year: "Car Year",
     yearPlaceHolder: "YYYY",
     enterYourContactInfo: "Enter your Contact Info",
     yourFullName: "Your Full Name",
     yourMobileNumber: "Your Mobile Number",
    whyShouldYouSellYourCar: "Why should you sell your car with us?",
    weSupportYouFromStartToFinish: "We support you from start to finish",
    weHaveStreamlind: "We have streamlined the process to sell your car online for quick payment to get your free cash offer.",
    readyToSell: "Ready to sell your car?",
    sendYourInquiry: "Send Your Inquiry",
    sendNewInquiry: "Send New Inquiry",
    whyOurService: "Why use our services?",
    weOperates24Hours: "We operate 24 hour-a-day / 7 day-a-week telephone, email & remote support ",
    weOperates24HoursBr: "services that is staffed to handle any issue or question",
    easyProcess: "Easy Process",
    easyProcessContent: "We help you save time and effort. We master how to sell a car privately and have simplified the process of selling a vehicle to make it hassle-free.",
    getTheBest: "Get The Best Return",
    getTheBestContent: "Get the most money for your car. Reach serious buyers. Avoid lowball offers. Use our valuation tools for a better price when selling your car.",
    dedicatedTeam: "Dedicated Team",
    dedicatedTeamContent: "Our seller experts are here to help you at every step of the way via email, phone, or chat all the week days! They help you find real buyers for your car and finalize your deal fast.",
    getPreparedBeforeCall: "Get prepared before our call",
    requiredDocs: "Required Documents & Procedures",
    doc1: "The car must be brought in good working condition.",
    doc2: "In case the chassis is not OK, we'll do a registration test.",
    doc4: "If the item is sold, the check will be deposit in your bank account after 10 working days from the time of auction’s conclusion.",
    doc6: "For the classic cars, trucks and heavy equipment, you must bring export test.",
    doc7: "For the equipment (generator, scissor lift, electric forklift ..... etc) Tax invoice is required.",
    doc8: "We'll do a comprehensive test.",
    requiredDoc: "Required Documentation",
    emiratesId: "Emirates ID",
    possessionCertificate: "Possession certificate",
    possessionCertificateSubHeader: "(Dubai certificate or transfer to Dubai)",
    bankDetails: "Bank account details",
    buyNewAndUsed: "Buy new and used cars in UAE, shipping and delivery service are available, Sell your car at the highest price online with no worries visiting cars show rooms.",
    followTheFirstAndTheLargest: "Follow the first and the largest online auction in UAE and Middle East",
    errorMsgResponse: "* All fields are required to be filled",
    successHeader: "Your inquiry has been sent successfully",
    successContent: "Your message has been sent successfully. Thank you for your enquiry. It has been forwarded to the relevant department and will be dealt within 24 hours"
 },
 ar: {
     lang: "English",
     sellingYourCarNow: "بيع سيارتك الآن",
     easierThanEver: "أسهل من أي وقت مضى",
     startToday: "إبدأ اليوم",
     howItWorks: "كيف تعمل ؟",
     sellYourCarInThreeSimpleSteps: "بيع سيارتك في ثلاث خطوات بسيطة",
     submitYourCar: "أرسل سيارتك",
     enterYourCarDetails: "أدخل تفاصيل سيارتك لفحصها في مزاد الإمارات.",
     receiveOffer: "تلقي التقييم والعرض",
     weWillCheckCar: "سوف نتحقق من سيارتك ونوفر لك سعر شراء معتمد.",
     getThePayment: "احصل على دفعتك",
     afterPriceIsAgree: "بعد الاتفاق على سعر لسيارتك ، سنقوم بتبادل النقود في اليوم الذي يناسبك.",
     yourCarWillBeSold: "سيتم بيع سيارتك بالمزايدة",
     startPriceItWillBeSold: "قمت بتعيين سعر البداية سيتم بيعه لأعلى مزايد",
     youAreJustOneClick: "أنت على بعد نقرة واحدة من بيع سيارتك",
     enterCarDetail: "أدخل تفاصيل سيارتك",
     carBrand: "ماركة السيارة",
     carModel: "طراز السيارة",
     enterYourContactInfo: "أدخل معلومات الاتصال الخاصة بك",
     yearPlaceHolder:"السنه",
     yourFullName: "إسمك بالكامل",
     yourMobileNumber: "رقم هاتفك",
     whyShouldYouSellYourCar: "لماذا يجب عليك بيع سيارتك معنا؟",
    weSupportYouFromStartToFinish: "نحن ندعمك من البداية إلى النهاية",
    weHaveStreamlind: "لقد قمنا بتبسيط عملية بيع سيارتك عبر الإنترنت للدفع السريع للحصول على عرض نقدي مجاني.",
    readyToSell: "جاهز لبيع سيارتك؟",
    sendYourInquiry: "أرسل استفسارك",
    sendNewInquiry: "أرسل استفسار جديد",
    whyOurService: "لماذا نستخدم خدماتنا؟",
    weOperates24Hours: "نحن نعمل على مدار 24 ساعة / 7 أيام في الأسبوع عبر الهاتف وخدمات البريد الإلكتروني والدعم عن بعد",
    weOperates24HoursBr: " والتي يتم توظيفها للتعامل مع أي مشكلة أو سؤال",

    easyProcess: "عملية سهلة",
    easyProcessContent: "نحن نساعدك على توفير الوقت والجهد. نحن نتقن كيفية بيع سيارة بشكل خاص وتبسيط عملية بيع سيارة لجعلها خالية من المتاعب.",
    getTheBest: "احصل على أفضل عائد",
    getTheBestContent: "احصل على أكبر قدر من المال لسيارتك. الوصول إلى مشترين جادين. تجنب عروض كرة منخفضة. استخدم أدوات التقييم الخاصة بنا للحصول على سعر أفضل عند بيع سيارتك.",
    dedicatedTeam: "فريق متخصص",
    dedicatedTeamContent: "خبراء البائعون هنا لمساعدتك في كل خطوة على الطريق عبر البريد الإلكتروني أو الهاتف أو الدردشة طوال أيام الأسبوع! فهي تساعدك في العثور على مشترين حقيقيين لسيارتك وإتمام صفقتك بسرعة.",
    getPreparedBeforeCall: "استعد قبل اتصالنا",
    requiredDocs: "المستندات والإجراءات المطلوبة",
    doc1: "يجب إحضار السيارة في حالة عمل جيدة .",
    doc2: "في حال لم يكن الهيكل جيدًا ، فسنقوم باختبار تسجيل.",
    doc4: "إذا تم بيع السلعة ، فسيتم إيداع الشيك في حسابك المصرفي بعد 10 أيام عمل من وقت انتهاء المزاد .",
    doc6: "بالنسبة للسيارات الكلاسيكية والشاحنات والمعدات الثقيلة ، يجب عليك إحضار اختبار التصدير فقط.",
    doc7: "للمعدات (مولد ، رافعة مقصية ، رافعة شوكية كهربائية ..... الخ) مطلوب فاتورة ضريبية.",
    doc8: "سنقوم باختبار شامل.",
    requiredDoc: "الوثائق المطلوبة",
    emiratesId: "هويه الإمارات",
    possessionCertificate: "شهادة حيازة",
    possessionCertificateSubHeader: "(شهادة دبي أو التحويل إلى دبي)",
    bankDetails: "تفاصيل الحساب المصرفي",
    buyNewAndUsed: "اشترِ سيارات جديدة ومستعملة في الإمارات العربية المتحدة ، وتتوفر خدمة الشحن والتسليم ، وقم ببيع سيارتك بأعلى سعر عبر الإنترنت دون قلق من زيارة صالات عرض السيارات.",
    followTheFirstAndTheLargest: "اتبع أول وأكبر مزاد على الإنترنت في الإمارات العربية المتحدة والشرق الأوسط",
    errorMsgResponse: "* يجب ملء جميع الحقول",
    successHeader: "تم إرسال استفسارك بنجاح",
    successContent: "تم ارسال رسالتك بنجاح. شكرا لاستفسارك. تم تحويله إلى القسم المختص وسيتم التعامل معه خلال 24 ساعة",
    year: "سنة الصنع",

 }
});